import React, { useState, useEffect } from "react";
import { DataQuery, useDataQuery, useDataMutation } from "@dhis2/app-runtime";
import i18n from "@dhis2/d2-i18n";
import classes from "./App.module.css";
import { CircularLoader } from "@dhis2/ui";
import { transRequest, transUpdateRequest } from "./utilities/requests";

import Sidenav from "./components/common/Sidenav";
import Dashboard from "./pages/Dashboard";
import Inventory from "./pages/StockOverview";
import Transactions from "./pages/StockHistory";

const MyApp = () => {
  /* State for handling navigation */
  const [activePage, setActivePage] = useState("Dashboard");

  function activePageHandler(page) {
    setActivePage(page);
  }

  // 3. For Stock Update:
  //    const [updateStock] = useDataMutation(stockUpdateRequest);
  //     useEffect(() => {
  //       updateStock({
  //           dataElement: "W1XtQhP6BGd",
  //           categoryOptionCombo: "J2Qf1jtZuj8",  //endBalance
  //           value: "321",
  //       })
  //     }, [])

  //4. For Transaction Update:
  //   const [transData, setTransData] = useState(mockData);
  //   const [updateTrans] = useDataMutation(transUpdateRequest);
  //   useEffect(() => {
  //     updateTrans({ data: transData });
  //   }, []);

  const { loading, error, data } = useDataQuery(transRequest);
  if (error)
    return (
      <span>
        ERROR in getting transaction/stock history data: {error.message}
      </span>
    );
  if (loading) return <CircularLoader large />;
  if (data) {
    let transactionData = data.transactionHistory.data;
    return (
      <div className={classes.container}>
        <div className={classes.sidenav}>
          <Sidenav
            activePage={activePage}
            activePageHandler={activePageHandler}
          />
        </div>
        <section className={classes.content}>
          {activePage === "Dashboard" && (
            <Dashboard transactionData={transactionData} />
          )}
          {activePage === "StockOverview" && (
            <Inventory transactionData={transactionData} />
          )}
          {activePage === "StockHistory" && (
            <Transactions transactionData={transactionData} />
          )}
        </section>
      </div>
    );
  }
};

export default MyApp;

const mockData = [
  {
    amount: -3,
    balanceAfterTrans: 197,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-08-29",
    dispensedBy: "John",
    dispensedTo: "Jenny",
    time: "14:20:00",
  },
  {
    amount: -2,
    balanceAfterTrans: 98,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-08-28",
    dispensedBy: "Smith",
    dispensedTo: "Andy",
    time: "13:22:00",
  },
  {
    amount: -8,
    balanceAfterTrans: 392,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-08-28",
    dispensedBy: "Tim",
    dispensedTo: "Bob",
    time: "18:27:00",
  },
  {
    amount: -3,
    balanceAfterTrans: 97,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-08-28",
    dispensedBy: "Sara",
    dispensedTo: "Mia",
    time: "09:45:00",
  },
  {
    amount: -4,
    balanceAfterTrans: 62,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-08-26",
    dispensedBy: "Ella",
    dispensedTo: "Liam",
    time: "16:18:00",
  },
  {
    amount: -7,
    balanceAfterTrans: 54,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-08-25",
    dispensedBy: "Oliver",
    dispensedTo: "Sophie",
    time: "11:30:00",
  },
  {
    amount: -25,
    balanceAfterTrans: 45,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-08-23",
    dispensedBy: "Lucas",
    dispensedTo: "James",
    time: "17:12:00",
  },
  {
    amount: -18,
    balanceAfterTrans: 27,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-08-21",
    dispensedBy: "Noah",
    dispensedTo: "Mia",
    time: "14:56:00",
  },
  {
    amount: -10,
    balanceAfterTrans: 42,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-08-21",
    dispensedBy: "William",
    dispensedTo: "James",
    time: "10:03:00",
  },
  {
    amount: -12,
    balanceAfterTrans: 97,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-08-21",
    dispensedBy: "James",
    dispensedTo: "Sophia",
    time: "13:40:00",
  },
  {
    amount: -3,
    balanceAfterTrans: 40,
    commodityId: "d9vZ3HOlzAd",
    commodityName: "Antenatal Corticosteroids",
    date: "2023-08-20",
    dispensedBy: "Benjamin",
    dispensedTo: "Lucy",
    time: "08:15:00",
  },
  {
    amount: -8,
    balanceAfterTrans: 32,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-08-20",
    dispensedBy: "Henry",
    dispensedTo: "Harper",
    time: "15:59:00",
  },
  {
    amount: -3,
    balanceAfterTrans: 44,
    commodityId: "Boy3QwztgeZ",
    commodityName: "Amoxicillin",
    date: "2023-08-18",
    dispensedBy: "Liam",
    dispensedTo: "Ella",
    time: "12:04:00",
  },
  {
    amount: -4,
    balanceAfterTrans: 20,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-08-18",
    dispensedBy: "Mason",
    dispensedTo: "Aria",
    time: "19:27:00",
  },
  {
    amount: -5,
    balanceAfterTrans: 192,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-08-18",
    dispensedBy: "Luna",
    dispensedTo: "Ethan",
    time: "08:35:00",
  },
  {
    amount: 50,
    balanceAfterTrans: 192,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-08-17",
    dispensedBy: "Luna",
    dispensedTo: "Ethan",
    time: "08:35:00",
  },
  {
    amount: -7,
    balanceAfterTrans: 33,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-08-17",
    dispensedBy: "Harper",
    dispensedTo: "Jackson",
    time: "14:12:00",
  },
  {
    amount: -1,
    balanceAfterTrans: 97,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-08-15",
    dispensedBy: "Aiden",
    dispensedTo: "Avery",
    time: "16:48:00",
  },
  {
    amount: -12,
    balanceAfterTrans: 49,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-08-15",
    dispensedBy: "Emma",
    dispensedTo: "Sebastian",
    time: "10:57:00",
  },
  {
    amount: -4,
    balanceAfterTrans: 388,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-08-12",
    dispensedBy: "Nora",
    dispensedTo: "James",
    time: "15:03:00",
  },
  {
    amount: -6,
    balanceAfterTrans: 64,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-08-12",
    dispensedBy: "Lucy",
    dispensedTo: "James",
    time: "12:44:00",
  },
  {
    amount: -1,
    balanceAfterTrans: 96,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-08-12",
    dispensedBy: "Eva",
    dispensedTo: "Benjamin",
    time: "09:12:00",
  },
  {
    amount: -9,
    balanceAfterTrans: 70,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-08-11",
    dispensedBy: "Ava",
    dispensedTo: "William",
    time: "13:55:00",
  },
  {
    amount: -4,
    balanceAfterTrans: 56,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-08-11",
    dispensedBy: "Harper",
    dispensedTo: "Mia",
    time: "18:14:00",
  },
  {
    amount: -11,
    balanceAfterTrans: 67,
    commodityId: "Boy3QwztgeZ",
    commodityName: "Amoxicillin",
    date: "2023-08-10",
    dispensedBy: "Liam",
    dispensedTo: "Ella",
    time: "11:30:00",
  },
  {
    amount: -3,
    balanceAfterTrans: 34,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-08-09",
    dispensedBy: "Jackson",
    dispensedTo: "Sophie",
    time: "09:45:00",
  },
  {
    amount: -5,
    balanceAfterTrans: 92,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-08-07",
    dispensedBy: "Aiden",
    dispensedTo: "Eva",
    time: "14:20:00",
  },
  {
    amount: -17,
    balanceAfterTrans: 51,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-08-05",
    dispensedBy: "Smith",
    dispensedTo: "Andy",
    time: "17:02:00",
  },
  {
    amount: -6,
    balanceAfterTrans: 29,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-08-02",
    dispensedBy: "Nora",
    dispensedTo: "Daniel",
    time: "10:10:00",
  },
  {
    amount: -6,
    balanceAfterTrans: 45,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-08-02",
    dispensedBy: "Tim",
    dispensedTo: "Sophia",
    time: "15:30:00",
  },
  {
    amount: -7,
    balanceAfterTrans: 89,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-08-02",
    dispensedBy: "Lucy",
    dispensedTo: "James",
    time: "13:55:00",
  },
  {
    amount: -5,
    balanceAfterTrans: 40,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-08-01",
    dispensedBy: "Benjamin",
    dispensedTo: "Mia",
    time: "14:28:00",
  },
  {
    amount: -9,
    balanceAfterTrans: 75,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-07-31",
    dispensedBy: "Oliver",
    dispensedTo: "Aria",
    time: "16:42:00",
  },
  {
    amount: 18,
    balanceAfterTrans: 56,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-06-30",
    dispensedBy: "Sarah",
    dispensedTo: "Emily",
    time: "10:15:00",
  },
  {
    amount: 5,
    balanceAfterTrans: 15,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-06-29",
    dispensedBy: "Lucas",
    dispensedTo: "Olivia",
    time: "09:30:00",
  },
  {
    amount: 10,
    balanceAfterTrans: 42,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-06-29",
    dispensedBy: "Ella",
    dispensedTo: "Liam",
    time: "15:45:00",
  },
  {
    amount: 25,
    balanceAfterTrans: 36,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-06-29",
    dispensedBy: "Mia",
    dispensedTo: "Noah",
    time: "17:20:00",
  },
  {
    amount: 15,
    balanceAfterTrans: 63,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-06-27",
    dispensedBy: "Aiden",
    dispensedTo: "Sophia",
    time: "11:10:00",
  },
  {
    amount: 12,
    balanceAfterTrans: 23,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-06-27",
    dispensedBy: "Ethan",
    dispensedTo: "Ava",
    time: "12:55:00",
  },
  {
    amount: 20,
    balanceAfterTrans: 33,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-06-25",
    dispensedBy: "Liam",
    dispensedTo: "Oliver",
    time: "14:40:00",
  },
  {
    amount: 30,
    balanceAfterTrans: 58,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-06-23",
    dispensedBy: "Emma",
    dispensedTo: "James",
    time: "16:25:00",
  },
  {
    amount: 8,
    balanceAfterTrans: 25,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-06-20",
    dispensedBy: "Ava",
    dispensedTo: "Charlotte",
    time: "08:30:00",
  },
  {
    amount: 17,
    balanceAfterTrans: 41,
    commodityId: "d9vZ3HOlzAd",
    commodityName: "Antenatal Corticosteroids",
    date: "2023-06-20",
    dispensedBy: "Noah",
    dispensedTo: "Lily",
    time: "10:45:00",
  },
  {
    amount: 22,
    balanceAfterTrans: 47,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-06-20",
    dispensedBy: "William",
    dispensedTo: "Ella",
    time: "13:05:00",
  },
  {
    amount: 9,
    balanceAfterTrans: 18,
    commodityId: "Boy3QwztgeZ",
    commodityName: "Amoxicillin",
    date: "2023-06-18",
    dispensedBy: "Oliver",
    dispensedTo: "Lucas",
    time: "09:55:00",
  },
  {
    amount: 13,
    balanceAfterTrans: 31,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-06-18",
    dispensedBy: "Emily",
    dispensedTo: "Sophia",
    time: "11:30:00",
  },
  {
    amount: 19,
    balanceAfterTrans: 35,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-06-18",
    dispensedBy: "Mason",
    dispensedTo: "William",
    time: "14:15:00",
  },
  {
    amount: 14,
    balanceAfterTrans: 22,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-06-16",
    dispensedBy: "Charlotte",
    dispensedTo: "Aiden",
    time: "08:40:00",
  },
  {
    amount: 28,
    balanceAfterTrans: 45,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-06-16",
    dispensedBy: "James",
    dispensedTo: "Olivia",
    time: "10:10:00",
  },
  {
    amount: 17,
    balanceAfterTrans: 79,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-06-16",
    dispensedBy: "Alice",
    dispensedTo: "Eve",
    time: "10:15:00",
  },
  {
    amount: 6,
    balanceAfterTrans: 23,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-06-16",
    dispensedBy: "John",
    dispensedTo: "Linda",
    time: "16:45:00",
  },
  {
    amount: 12,
    balanceAfterTrans: 18,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-06-15",
    dispensedBy: "Sarah",
    dispensedTo: "Mike",
    time: "09:30:00",
  },
  {
    amount: 9,
    balanceAfterTrans: 51,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-06-15",
    dispensedBy: "Laura",
    dispensedTo: "Kevin",
    time: "14:10:00",
  },
  {
    amount: 25,
    balanceAfterTrans: 33,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-06-14",
    dispensedBy: "Megan",
    dispensedTo: "David",
    time: "11:55:00",
  },
  {
    amount: 18,
    balanceAfterTrans: 22,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-06-12",
    dispensedBy: "Paul",
    dispensedTo: "Lisa",
    time: "17:20:00",
  },
  {
    amount: 30,
    balanceAfterTrans: 45,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-06-12",
    dispensedBy: "Ethan",
    dispensedTo: "Olivia",
    time: "12:40:00",
  },
  {
    amount: 5,
    balanceAfterTrans: 15,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-06-12",
    dispensedBy: "Sophia",
    dispensedTo: "James",
    time: "08:05:00",
  },
  {
    amount: 11,
    balanceAfterTrans: 26,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-06-10",
    dispensedBy: "Nathan",
    dispensedTo: "Emily",
    time: "14:55:00",
  },
  {
    amount: 22,
    balanceAfterTrans: 37,
    commodityId: "d9vZ3HOlzAd",
    commodityName: "Antenatal Corticosteroids",
    date: "2023-06-10",
    dispensedBy: "Logan",
    dispensedTo: "Ava",
    time: "11:30:00",
  },
  {
    amount: 13,
    balanceAfterTrans: 41,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-06-09",
    dispensedBy: "Aiden",
    dispensedTo: "Sophie",
    time: "09:10:00",
  },
  {
    amount: 8,
    balanceAfterTrans: 12,
    commodityId: "Boy3QwztgeZ",
    commodityName: "Amoxicillin",
    date: "2023-06-08",
    dispensedBy: "Ella",
    dispensedTo: "Henry",
    time: "16:25:00",
  },
  {
    amount: 16,
    balanceAfterTrans: 22,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-06-07",
    dispensedBy: "Grace",
    dispensedTo: "Michael",
    time: "13:40:00",
  },
  {
    amount: 14,
    balanceAfterTrans: 31,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-06-03",
    dispensedBy: "Liam",
    dispensedTo: "Charlotte",
    time: "10:50:00",
  },
  {
    amount: 7,
    balanceAfterTrans: 14,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-06-03",
    dispensedBy: "Oliver",
    dispensedTo: "Evelyn",
    time: "12:15:00",
  },
  {
    amount: 19,
    balanceAfterTrans: 42,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-06-01",
    dispensedBy: "Mia",
    dispensedTo: "Ethan",
    time: "17:30:00",
  },
  {
    amount: 10,
    balanceAfterTrans: 40,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-06-01",
    dispensedBy: "Noah",
    dispensedTo: "Avery",
    time: "09:55:00",
  },
  {
    amount: 23,
    balanceAfterTrans: 29,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-05-28",
    dispensedBy: "Lily",
    dispensedTo: "William",
    time: "15:45:00",
  },
  {
    amount: 21,
    balanceAfterTrans: 43,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-05-28",
    dispensedBy: "Mason",
    dispensedTo: "Victoria",
    time: "14:20:00",
  },
  {
    amount: 15,
    balanceAfterTrans: 33,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-05-27",
    dispensedBy: "Zoe",
    dispensedTo: "Jackson",
    time: "16:10:00",
  },
  {
    amount: 11,
    balanceAfterTrans: 23,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-05-25",
    dispensedBy: "Samuel",
    dispensedTo: "Lillian",
    time: "12:35:00",
  },
  {
    amount: 24,
    balanceAfterTrans: 32,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-05-25",
    dispensedBy: "Elijah",
    dispensedTo: "Harper",
    time: "10:05:00",
  },
  {
    amount: 13,
    balanceAfterTrans: 26,
    commodityId: "d9vZ3HOlzAd",
    commodityName: "Antenatal Corticosteroids",
    date: "2023-05-24",
    dispensedBy: "Aiden",
    dispensedTo: "Zoe",
    time: "15:15:00",
  },
  {
    amount: 7,
    balanceAfterTrans: 19,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-05-20",
    dispensedBy: "Ella",
    dispensedTo: "Liam",
    time: "17:40:00",
  },
  {
    amount: 12,
    balanceAfterTrans: 24,
    commodityId: "Boy3QwztgeZ",
    commodityName: "Amoxicillin",
    date: "2023-05-20",
    dispensedBy: "Olivia",
    dispensedTo: "Ethan",
    time: "09:55:00",
  },
  {
    amount: 8,
    balanceAfterTrans: 18,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-05-19",
    dispensedBy: "Charlotte",
    dispensedTo: "Mason",
    time: "14:30:00",
  },
  {
    amount: 16,
    balanceAfterTrans: 32,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-05-19",
    dispensedBy: "James",
    dispensedTo: "Lily",
    time: "11:05:00",
  },
  {
    amount: 9,
    balanceAfterTrans: 22,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-05-18",
    dispensedBy: "Evelyn",
    dispensedTo: "Elijah",
    time: "13:25:00",
  },
  {
    amount: 19,
    balanceAfterTrans: 41,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-05-18",
    dispensedBy: "Liam",
    dispensedTo: "Mia",
    time: "15:50:00",
  },
  {
    amount: 14,
    balanceAfterTrans: 29,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-05-16",
    dispensedBy: "Ella",
    dispensedTo: "Noah",
    time: "09:15:00",
  },
  {
    amount: 28,
    balanceAfterTrans: 34,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-05-16",
    dispensedBy: "Zoe",
    dispensedTo: "Aiden",
    time: "17:30:00",
  },
  {
    amount: 10,
    balanceAfterTrans: 26,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-05-16",
    dispensedBy: "Ethan",
    dispensedTo: "Olivia",
    time: "16:20:00",
  },
  {
    amount: -23,
    balanceAfterTrans: 34,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-05-15",
    dispensedBy: "John",
    dispensedTo: "Jenny",
    time: "14:20:00",
  },
  {
    amount: 44,
    balanceAfterTrans: 11,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-05-14",
    dispensedBy: "Smith",
    dispensedTo: "Andy",
    time: "13:22:00",
  },
  {
    amount: 32,
    balanceAfterTrans: 12,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-05-12",
    dispensedBy: "Tim",
    dispensedTo: "Bob",
    time: "18:27:00",
  },
  {
    amount: 12,
    balanceAfterTrans: 45,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-05-12",
    dispensedBy: "Alice",
    dispensedTo: "Eve",
    time: "10:15:00",
  },
  {
    amount: -7,
    balanceAfterTrans: 29,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-05-10",
    dispensedBy: "David",
    dispensedTo: "Olivia",
    time: "21:45:00",
  },
  {
    amount: 18,
    balanceAfterTrans: 42,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-05-10",
    dispensedBy: "Sarah",
    dispensedTo: "Liam",
    time: "15:30:00",
  },
  {
    amount: 25,
    balanceAfterTrans: 33,
    commodityId: "Boy3QwztgeZ",
    commodityName: "Amoxicillin",
    date: "2023-05-09",
    dispensedBy: "Lucas",
    dispensedTo: "Chloe",
    time: "09:10:00",
  },
  {
    amount: -16,
    balanceAfterTrans: 38,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-05-09",
    dispensedBy: "Mia",
    dispensedTo: "Noah",
    time: "12:55:00",
  },
  {
    amount: 14,
    balanceAfterTrans: 21,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-05-09",
    dispensedBy: "Ella",
    dispensedTo: "Mason",
    time: "16:40:00",
  },
  {
    amount: 30,
    balanceAfterTrans: 39,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-05-08",
    dispensedBy: "Jackson",
    dispensedTo: "Ava",
    time: "11:05:00",
  },
  {
    amount: -5,
    balanceAfterTrans: 28,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-05-06",
    dispensedBy: "Harper",
    dispensedTo: "William",
    time: "19:20:00",
  },
  {
    amount: 22,
    balanceAfterTrans: 37,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-05-05",
    dispensedBy: "Sophia",
    dispensedTo: "Ethan",
    time: "08:30:00",
  },
  {
    amount: 38,
    balanceAfterTrans: 49,
    commodityId: "d9vZ3HOlzAd",
    commodityName: "Antenatal Corticosteroids",
    date: "2023-05-05",
    dispensedBy: "Aiden",
    dispensedTo: "Oliver",
    time: "07:15:00",
  },
  {
    amount: -19,
    balanceAfterTrans: 26,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-05-04",
    dispensedBy: "Aria",
    dispensedTo: "Elijah",
    time: "11:50:00",
  },
  {
    amount: 10,
    balanceAfterTrans: 36,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-05-04",
    dispensedBy: "Evelyn",
    dispensedTo: "Henry",
    time: "15:55:00",
  },
  {
    amount: -12,
    balanceAfterTrans: 23,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-05-04",
    dispensedBy: "Camila",
    dispensedTo: "Sebastian",
    time: "10:40:00",
  },
  {
    amount: -23,
    balanceAfterTrans: 34,
    commodityId: "W1XtQhP6BGd",
    commodityName: "Resuscitation Equipment",
    date: "2023-05-03",
    dispensedBy: "John",
    dispensedTo: "Jenny",
    time: "14:20:00",
  },
  {
    amount: 44,
    balanceAfterTrans: 11,
    commodityId: "o15CyZiTvxa",
    commodityName: "Magnesium Sulfate",
    date: "2023-05-03",
    dispensedBy: "Smith",
    dispensedTo: "Andy",
    time: "13:22:00",
  },
  {
    amount: 32,
    balanceAfterTrans: 12,
    commodityId: "TCfIC3NDgQK",
    commodityName: "Zinc",
    date: "2023-05-03",
    dispensedBy: "Tim",
    dispensedTo: "Bob",
    time: "18:27:00",
  },
  {
    amount: 12,
    balanceAfterTrans: 45,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-05-02",
    dispensedBy: "Alice",
    dispensedTo: "Eve",
    time: "10:15:00",
  },
  {
    amount: -7,
    balanceAfterTrans: 29,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-05-02",
    dispensedBy: "David",
    dispensedTo: "Olivia",
    time: "21:45:00",
  },
  {
    amount: 18,
    balanceAfterTrans: 42,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-05-01",
    dispensedBy: "Sarah",
    dispensedTo: "Liam",
    time: "15:30:00",
  },
  {
    amount: 25,
    balanceAfterTrans: 33,
    commodityId: "Boy3QwztgeZ",
    commodityName: "Amoxicillin",
    date: "2023-05-01",
    dispensedBy: "Lucas",
    dispensedTo: "Chloe",
    time: "09:10:00",
  },
  {
    amount: -16,
    balanceAfterTrans: 38,
    commodityId: "Lz8MM2Y9DNh",
    commodityName: "Oral Rehydration Salts",
    date: "2023-04-29",
    dispensedBy: "Mia",
    dispensedTo: "Noah",
    time: "12:55:00",
  },
  {
    amount: 14,
    balanceAfterTrans: 21,
    commodityId: "f27B1G7B3m3",
    commodityName: "Misoprostol",
    date: "2023-04-29",
    dispensedBy: "Ella",
    dispensedTo: "Mason",
    time: "16:40:00",
  },
  {
    amount: 30,
    balanceAfterTrans: 39,
    commodityId: "dY4OCwl0Y7Y",
    commodityName: "Female Condoms",
    date: "2023-04-24",
    dispensedBy: "Jackson",
    dispensedTo: "Ava",
    time: "11:05:00",
  },
  {
    amount: -5,
    balanceAfterTrans: 28,
    commodityId: "Dkapzovo8Ll",
    commodityName: "Implants",
    date: "2023-04-24",
    dispensedBy: "Harper",
    dispensedTo: "William",
    time: "19:20:00",
  },
  {
    amount: 22,
    balanceAfterTrans: 37,
    commodityId: "WjDoIR27f31",
    commodityName: "Chlorhexidine",
    date: "2023-04-20",
    dispensedBy: "Sophia",
    dispensedTo: "Ethan",
    time: "08:30:00",
  },
  {
    amount: 38,
    balanceAfterTrans: 49,
    commodityId: "d9vZ3HOlzAd",
    commodityName: "Antenatal Corticosteroids",
    date: "2023-04-18",
    dispensedBy: "Aiden",
    dispensedTo: "Oliver",
    time: "07:15:00",
  },
  {
    amount: -19,
    balanceAfterTrans: 26,
    commodityId: "hJNC4Bu2Mkv",
    commodityName: "Oxytocin",
    date: "2023-04-17",
    dispensedBy: "Aria",
    dispensedTo: "Elijah",
    time: "11:50:00",
  },
  {
    amount: 10,
    balanceAfterTrans: 36,
    commodityId: "BXgDHhPdFVU",
    commodityName: "Emergency Contraception",
    date: "2023-04-15",
    dispensedBy: "Evelyn",
    dispensedTo: "Henry",
    time: "15:55:00",
  },
  {
    amount: -12,
    balanceAfterTrans: 23,
    commodityId: "JIazHXNSnFJ",
    commodityName: "Injectable Antibiotics",
    date: "2023-04-15",
    dispensedBy: "Camila",
    dispensedTo: "Sebastian",
    time: "10:40:00",
  },
];
